### ISSUE TITLE
Install fail via tty on Raspberry pi 2b

### ISSUE THREAD

**Issue by kane-thornwyrd** [YunoHost-Apps/onlyoffice_ynh#19]
Here the log: [https://paste.yunohost.org/raw/ewiqujodoq](https://paste.yunohost.org/raw/ewiqujodoq)
Here the specs:
OS: Raspbian GNU/Linux 9.9 (stretch) armv7l 
Model: Raspberry Pi 2 Model B Rev 1.1 
Kernel: 4.14.79-v7+ 
Packages: 864 
Shell: bash 4.4.12 
CPU: ARMv7 rev 5 (v7l) (4) @ 0.9GHz 
Memory: 363MB / 927MB

scenario:
`admin@minecraft:~ $ sudo yunohost app install https://github.com/YunoHost-Apps/onlyoffice_ynh`

**Comment by kane-thornwyrd** [comment]
ping @maniackcrudelis , does @liberodark have irl issues/is in holidays or something justifying that he doesn't address issues since the 25th March and keep having this sort of official evaluation ? 
![Capture d’écran de 2019-07-13 03-49-33](https://user-images.githubusercontent.com/625236/61165482-562ffc80-a521-11e9-833c-977e3e000e02.png)

**Comment by decentral1se** [comment]
Hey there @kane-thornwyrd, we're all doing our best at volunteering, let's respect that.

I believe your isuse was fixed in https://github.com/YunoHost-Apps/onlyoffice_ynh/commit/a49aa0a5a67b53a0601f4a6dafe780249b208218.

Please let us know if you're still having issues, I'm going to close this off for now.

Feel free to re-open and/or continue the discussion.
